(GH-93) Avoid CS0200 Serialization w/private set
When using private or internal sets, some systems will run into the
CS0200 issue. The error manifests itself in the following manner:

```
Error serializing type chocolatey.infrastructure.app.domain.Registry:
System.InvalidOperationException: Unable to generate a temporary class
(result=1
).
error CS0200: Property or indexer
'chocolatey.infrastructure.app.domain.Registry
.RegistryKeys' cannot be assigned to -- it is read only
error CS0200: Property or indexer
'chocolatey.infrastructure.app.domain.Registry
.RegistryKeys' cannot be assigned to -- it is read only
```

Leaving a note where it is required not to convert to private sets,
even though that is preferred and making the set public is how this
error is avoided.