(GH-1287) API - Ensure dll can work w/licensed code
When working to determine the issue with the licensed code, a couple of
incompatibilities between choco.exe and chocolatey.dll were found that
were preventing Chocolatey from allowing the licensed edition to work
with the DLL.

Specifically, `System.Reflection.TargetInvocationException
System.MethodAccessException: Attempt by method to access method
failed` as methods for checking some things were missing (internalized)
in the DLL, where they were available in the EXE. Adjust to allow
for those items to be loaded.